
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vipin
 */
public class makeit extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form makeit
     */
    boolean isdifferent;
    JTextField[][] a= new JTextField[9][9];
    Random r=new Random();
    JButton b=new JButton("Make It");
    public makeit() {
         for(int i=0;i<9;i++){
           for(int j=0;j<9;j++){
                a[i][j]=new JTextField();
            }
        }
        for(int i=0;i<9;i++)     //loops to add jtextfield on jframe
            for(int j=0;j<9;j++)
            this.add(a[i][j]);
        int tempi=0,tempj=0;
        for(int i=0;i<9;i++){            //loops to set bounds of jtextfield
           for(int j=0;j<9;j++){
                a[i][j].setBounds(j+tempi, i+tempj, 35, 35);
                tempi=tempi+30; 
              }
               tempj=tempj+30;  
               tempi=0;
            }
        this.add(b);
        b.setBounds(100,300,80,30);
         b.addActionListener(new ActionListener(){  
              public void actionPerformed(ActionEvent e){  
             for(int i=0;i<9;i++){
                 for(int j=0;j<9;j++){
                     isdifferent=true;
                     while(isdifferent){
                         isdifferent=false;
                         a[i][j].setText(String.valueOf(r.nextInt(9)+1));
                         
                         for(int k=0;k<j;k++){
                         if(Integer.parseInt(a[i][k].getText())==Integer.parseInt(a[i][j].getText())){
                             isdifferent=true;
                             break;
                         }
                       }
                         for(int k=0;k<i;k++){
                         if(Integer.parseInt(a[k][j].getText())==Integer.parseInt(a[i][j].getText())){
                             isdifferent=true;
                             break;
                         }
                     }
                 }
             }
             }}

             private void sleep(int par) {
                 throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
             }
         }); 
        initComponents();
       
    }
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(214, 214));
        setPreferredSize(new java.awt.Dimension(295, 400));
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makeit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makeit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makeit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makeit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makeit().setVisible(true);
           
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
