
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LKRK
 */
public class base extends javax.swing.JFrame {

    /**
     * Creates new form base
     */
    public void fun(String st){
        String d="",b="",o="",h="";
        if(st.equals("Decimal")){
        int i=Integer.parseInt(combot.getText());
        String s=Integer.toString(i);
        d=Integer.toString(i,10);
        b=Integer.toString(i,2);
        o=Integer.toString(i,8);
        h=Integer.toString(i,16);
        }
        if(st.equals("Binary")){
        int i=Integer.parseInt(combot.getText());
        String s=Integer.toString(i);
          d=Integer.toString(Integer.parseInt(s,2));
          b=combot.getText();
          o=Integer.toOctalString(Integer.parseInt(d));
          h=Integer.toHexString(Integer.parseInt(d));
        }
        if(st.equals("Octal")){
        int i=Integer.parseInt(combot.getText());
        String s=Integer.toString(i);
          d=Integer.toString(Integer.parseInt(s,8));
          b=Integer.toBinaryString(Integer.parseInt(d));
          o=combot.getText();
          h=Integer.toHexString(Integer.parseInt(d));
        }
        if(st.equals("Hexadecimal")){
          d=Integer.toString(Integer.parseInt(combot.getText(),16));
          b=Integer.toBinaryString(Integer.parseInt(d));
          o=Integer.toOctalString(Integer.parseInt(d));
          h=combot.getText();
        }
        decimalt.setText(d);
        binaryt.setText(b);
        octalt.setText(o);
        hext.setText(h);
    }
    public base() {
        initComponents();
        //this.setIconImage(new ImageIcon("src/tictactoe.png").getImage());
        this.setTitle("Base Converter");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        combo = new javax.swing.JComboBox<>();
        combot = new javax.swing.JTextField();
        binary = new javax.swing.JLabel();
        decimal = new javax.swing.JLabel();
        hex = new javax.swing.JLabel();
        octal = new javax.swing.JLabel();
        decimalt = new javax.swing.JTextField();
        octalt = new javax.swing.JTextField();
        binaryt = new javax.swing.JTextField();
        hext = new javax.swing.JTextField();
        calculate = new javax.swing.JButton();
        menu = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(348, 344));
        setMinimumSize(new java.awt.Dimension(368, 354));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Decimal", "Binary", "Octal", "Hexadecimal" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, 29));

        combot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotActionPerformed(evt);
            }
        });
        getContentPane().add(combot, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 27, 144, 29));

        binary.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        binary.setText("Binary");
        getContentPane().add(binary, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 135, 140, 25));

        decimal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        decimal.setText("Decimal");
        getContentPane().add(decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 90, 140, 25));

        hex.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        hex.setText("HexaDecimal");
        getContentPane().add(hex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 140, 25));

        octal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        octal.setText("Octal");
        getContentPane().add(octal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 140, 25));

        decimalt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimaltActionPerformed(evt);
            }
        });
        getContentPane().add(decimalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 86, 144, 29));
        getContentPane().add(octalt, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 186, 143, 29));
        getContentPane().add(binaryt, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 133, 144, 29));
        getContentPane().add(hext, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 233, 143, 29));

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 130, 40));

        jMenu4.setText("View");

        jMenuItem2.setText("Creator");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Exit");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        menu.add(jMenu4);

        jMenu2.setText("Help");

        jMenuItem1.setText("Instructions");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        menu.add(jMenu2);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        
    }//GEN-LAST:event_comboActionPerformed

    private void decimaltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimaltActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_decimaltActionPerformed

    private void combotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotActionPerformed
        
    }//GEN-LAST:event_combotActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        String st=(String)combo.getSelectedItem();
        fun(st);
    }//GEN-LAST:event_calculateActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          JOptionPane.showMessageDialog(menu,"Name:Lalit\nCollege:SIT\nRoll No:1612610030");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(menu,"This is a Software whre you can\n"
                + "convet a integer from any base to any other base.\n"
                + "I hope that you like it.");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(base.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new base().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel binary;
    private javax.swing.JTextField binaryt;
    private javax.swing.JButton calculate;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField combot;
    private javax.swing.JLabel decimal;
    private javax.swing.JTextField decimalt;
    private javax.swing.JLabel hex;
    private javax.swing.JTextField hext;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuBar menu;
    private javax.swing.JLabel octal;
    private javax.swing.JTextField octalt;
    // End of variables declaration//GEN-END:variables
}
